parameters:
    a_vtehik_alarm.alarms_path: ''

services:
    a_vtehik_alarm.alarm_manager:
        class: AVtehik\AlarmBundle\Services\AlarmManager
        arguments: [%a_vtehik_alarm.alarms_path%]

    a_vtehik_alarm.command.executor:
        class: AVtehik\AlarmBundle\Command\ExecutorCommand
        arguments: [ @a_vtehik_alarm.alarm_manager ]

        tags:
           - { name: console.command }
    a_vtehik_alarm.twig.alarm_extension:
        class: AVtehik\AlarmBundle\Twig\AlarmBundleExtension
        tags:
            - { name: twig.extension }